### ISSUE TITLE
Any way to move the icon to the left?

### ISSUE THREAD

**Issue by TennoSerra** [michu2k/Accordion#50]
Its working great! I just want to move the icon to the left. 
![image](https://user-images.githubusercontent.com/68448913/188222023-8cae3eb3-3bb1-4edc-85cc-af1f397736ef.png)
I tried using ::before instead of ::after. I doesnt seem to work like that.
Other than that  It could be done with using flexbox to move it around. But then I would have to make the icon an img tag
This breaks the changing icon when opened or closed.
![image](https://user-images.githubusercontent.com/68448913/188221465-d906c5b8-aa0e-404d-abee-4824861509a0.png)
![image](https://user-images.githubusercontent.com/68448913/188223191-313d7192-88e1-4296-91f5-c5589c52a770.png)

This is an example of what im doing right now.(I replaced the + and - with Fontawesome Unicode Icons) 
Im sorry if this question seems stupid.
Thanks for any help!

**Comment by TennoSerra** [comment]
Its working great! I just want to move the icon to the left. 
![image](https://user-images.githubusercontent.com/68448913/188222023-8cae3eb3-3bb1-4edc-85cc-af1f397736ef.png)

**Comment by michu2k** [comment]
Hi @TennoSerra 
To move the icon to the left, you need to change position from right to left and add an additional spacing on the left side of the trigger. Here's a quick example of how you can do it:

HTML:
```html
<button class="ac-trigger ac-trigger-left">....</button>
```

CSS:
```CSS
  .ac .ac-trigger-left {
    padding: 10px 10px 10px 30px;
  }

  .ac .ac-trigger-left::after {
    content: "+"; /* FontAwesome icon */
    left: 10px;
    right: auto;
  }

  .ac.is-active > .ac-header .ac-trigger-left::after {
    content: "–";  /* FontAwesome icon */
  }
```
